CREATE TABLE IF NOT EXISTS subscription(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
                                        company_name VARCHAR(255),
                                        edition VARCHAR(255),
                                        status VARCHAR(255),
                                        market_place_base_url VARCHAR(255));
CREATE TABLE IF NOT EXISTS user_account(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
                                        openid VARCHAR(255),
                                        firstname VARCHAR(255),
                                        lastname VARCHAR(255),
                                        email VARCHAR(255),
                                        subscription_id INT);
INSERT INTO subscription(id, company_name, edition, status, market_place_base_url)
                 VALUES (1, 'Gods Algorithm inc', 'FREE', 'INITIALIZED', 'https://godsalgorithm.org');
INSERT INTO user_account(id, openid, firstname, lastname, email, subscription_id)
				VALUES (1, 'https://appdirectchallenge/openid/id/211aa367-f53b-4606-8887-80a381e0ef69', 'Prathiba', 'Ramachandramurthy', 'prathiba.r@gmail.com', 1);
INSERT INTO subscription(id, company_name, edition, status, market_place_base_url)
                 VALUES (2, 'Mystique Managed inc', 'FREE', 'INITIALIZED', 'https://mystiquemanaged.org');
INSERT INTO user_account(id, openid, firstname, lastname, email, subscription_id)
				VALUES (2, 'https://appdirectchallenge/openid/id/211aa367-f53b-4606-8887-80a381e0ef69', 'Issac', 'Newton', 'issac.newton@gmail.com', 2);