CREATE TABLE IF NOT EXISTS subscription(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
                                        company_name VARCHAR(255),
                                        edition VARCHAR(255),
                                        status VARCHAR(255),
                                        market_place_base_url VARCHAR(255));
CREATE TABLE IF NOT EXISTS user_account(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
                                        openid VARCHAR(255),
                                        firstname VARCHAR(255),
                                        lastname VARCHAR(255),
                                        email VARCHAR(255),
                                        subscription_id INT);